# Generated by Django 2.1.7 on 2019-05-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0002_auto_20190509_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='department_type',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_product', to='warehouseapp.Category', verbose_name='Categoria producte'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
