# Generated by Django 2.1.7 on 2019-05-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0003_auto_20190512_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogchange',
            unique_together=set(),
        ),
    ]
